---
abstract: 'Perl XS for comparing (matching) strings MasterMind style'
author:
  - 'Juan J. Merelo Guervós <jmerelo@(none)>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-MMM
no_index:
  directory:
    - t
    - inc
requires: {}
version: v0.0.3
